### ISSUE TITLE
assert(root_init_password != None)

### ISSUE THREAD

**Issue by shaunstoltz** [zettadb/kunlun#624]
shaunst@kunlu01:~/worker01/percona-8.0.18-bin-rel/dba_tools$ python2 install-mysql.py --config=./mysql_shard1.json --target_node_index=2
Installing mysql instance, please wait...
Traceback (most recent call last):
  File "install-mysql.py", line 266, in <module>
    args.shard_id, args.config, args.target_node_index, args.ha_mode, args.user)
  File "install-mysql.py", line 190, in __init__
    assert(root_init_password != None)
AssertionError

**Comment by shaunstoltz** [comment]
shaunst@kunlu01:~/worker01/percona-8.0.18-bin-rel/dba_tools$ python2 install-mysql.py --config=./mysql_shard1.json --target_node_index=0
Installing mysql instance, please wait...
mysql: [Warning] Using a password on the command line interface can be insecure.
mysql: [Warning] Using a password on the command line interface can be insecure.
shaunst@kunlu01:~/worker01/percona-8.0.18-bin-rel/dba_tools$ python2 install-mysql.py --config=./mysql_shard1.json --target_node_index=1
Installing mysql instance, please wait...
mysql: [Warning] Using a password on the command line interface can be insecure.
shaunst@kunlu01:~/worker01/percona-8.0.18-bin-rel/dba_tools$ python2 install-mysql.py --config=./mysql_shard1.json --target_node_index=2
Installing mysql instance, please wait...
Traceback (most recent call last):
  File "install-mysql.py", line 266, in <module>
    args.shard_id, args.config, args.target_node_index, args.ha_mode, args.user)
  File "install-mysql.py", line 190, in __init__
    assert(root_init_password != None)
AssertionError
shaunst@kunlu01:~/worker01/percona-8.0.18-bin-rel/dba_tools$

**Comment by shaunstoltz** [comment]
{
    "group_uuid":"e6578c3a-547e-11ea-9780-981fd1bd410d",
    "nodes":
    [
       {
          "is_primary":true,
          "ip": "127.0.0.1",
          "port": 6001,
          "xport": 60010,
          "mgr_port": 60011,
          "innodb_buffer_pool_size":"64MB",
	  "innodb_log_dir_path":"/kunlun/data01/inno/log",
          "data_dir_path":"/kunlun/data01",
          "log_dir_path":"/kunlun/data01/log",
          "user":"shaunst",
          "election_weight":50
       },

       {
          "is_primary":false,
          "ip": "127.0.0.1",
          "port": 6002,
          "xport": 60020,
          "mgr_port": 60021,
          "innodb_buffer_pool_size":"64MB",
	  "innodb_log_dir_path":"/kunlun/data02/inno/log",
          "data_dir_path":"/kunlun/data02",
          "log_dir_path":"/kunlun/data02/log",
          "user":"shaunst",
          "election_weight":50
       },

       {
          "is_primary":false,
          "ip": "127.0.0.1",
          "port": 6003,
          "xport": 60030,
          "mgr_port": 60031,
          "innodb_buffer_pool_size":"64MB",
	  "innodb_log_dir_path":"/kunlun/data03/inno/log",
          "data_dir_path":"/kunlun/data03",
          "log_dir_path":"/kunlun/data03/log",
          "user":"shaunst",
          "election_weight":50
       }

    ]
}

**Comment by shaunstoltz** [comment]
boring
